### ISSUE TITLE
how to tune extension in dev envrionment?

### ISSUE THREAD

**Issue by C-ra-ZY** [KipSong/vite-chrome-extension#1]
hi 
i just cloned this repo, installed all dependencies, and then run command: yarn dev
i can see ui from localhost:3000 indeed
but how may i debug extension via chrome, for example the communication between ui part and the background?
i can't find a dir containing manifest.json, so i can't add extension to chrome i think.

**Comment by KipSong** [comment]
因为启动的dev环境是web默认环境，chrome api 是没法在浏览器页面中使用的，项目里忘记介绍
vite build --watch 
然后刷新插件
