### ISSUE TITLE
chrome插件是个多页应用,应该如何配置呢,示例只有对于单页应用的使用

### ISSUE THREAD

**Issue by Mirrorgo** [KipSong/vite-chrome-extension#3]
chrome插件是个多页应用,应该如何配置呢,示例只有对于单页应用的使用

**Comment by KipSong** [comment]
Chrome 的Popup 它就是一个web容器，你说的多页面应用是？

**Comment by Mirrorgo** [comment]
> Chrome 的Popup 它就是一个web容器，你说的多页面应用是？

一般vite构建的应用是单页应用,然后用router切换嘛
而chrome插件其实有多个入口
popup.html,option.html等等,有的插件里面甚至还有自己写的一些其他页面,比如插入devtool里的penel的html文件(也可以说是多个web容器)
这样的话chrome插件实际上是个多页面应用,配置应该会有很多不同的地方,再加上contentscript,backgournd这样的js文件,此时应该如何弄呢

**Comment by KipSong** [comment]
在这里可以根据 Vite 本身的优势 在根目录去创建菜单，就会自动实现了
![image](https://user-images.githubusercontent.com/62598129/153981851-d5b5f0ec-2946-40be-ac52-8ed1300d9fcb.png)

**Comment by Mirrorgo** [comment]
搞定了,感谢
