### ISSUE TITLE
如何在contentScript中写jsx

### ISSUE THREAD

**Issue by Mirrorgo** [KipSong/vite-chrome-extension#4]
我希望能在contentScript中写jsx,于是我改了文件名称,变为tsx,并修改了各个路径和部分配置,此时如下图
![image](https://user-images.githubusercontent.com/55936306/153753767-8e686884-d7c2-46bd-a432-3d9a02d32a8a.png)
这个时候build,产物(见👆右侧内容)成功注入页面 ==> 两个节点都在
![image](https://user-images.githubusercontent.com/55936306/153753911-49394201-96f6-445c-a1dd-3292495425de.png)

然后我取消jsx的注释,build后的产物(见👇右侧内容)看似正常
![image](https://user-images.githubusercontent.com/55936306/153754018-d5e727df-1b8d-468d-a44a-73de0f1658a7.png)
但实际使用的时候,两个节点都消失了,build过程无任何报错
![image](https://user-images.githubusercontent.com/55936306/153754119-b72032b1-85e9-4e9c-b346-7ec907175ae9.png)

请问如何解决这种问题?

**Comment by KipSong** [comment]
这个项目有很多优化的地方，比如 contentScript 脚本中使用 JSX 来添加页面中的其他元素，
我给的建议是：
```
// contentScript 下
document.addEventListener('readystatechange', () => {
  if (document.readyState === 'interactive') {
    const registerScript = document.createElement('script');
    registerScript.src = chrome.runtime.getURL('yourscript.js');
    document.head.append(registerScript);
  }
});
```

使用这样的方式 需要修改一下 配置，你可以尝试 多编译的方式来让文件输出，根据插件的依赖文件，你可以设置为UMD格式

**Comment by Mirrorgo** [comment]
这里的多编译是什么意思?我在vite官方文档上没找到相关描述,搜索引擎也没找到
能否详细说说,如果有空的话希望能修改下项目做个示范,非常感谢

**Comment by KipSong** [comment]
```
scripts:{
 "build": "rimraf ./dist && tsc && vite build && rollup -c rollup.build.script.ts",
}
```
在这里可以通过 联合 命令去编译，主要是为了解决 Vite 不能多入口打包成不同的模块规范。
因此选择了 联合 脚本的方式进行 不同的 entry 打包不同模块。
