### ISSUE TITLE
css module在引入的时候没有代码路径提示

### ISSUE THREAD

**Issue by Mirrorgo** [KipSong/vite-chrome-extension#5]
我最近才开始尝试css module,然后发现:
css module在引入的时候没有代码路径提示
![image](https://user-images.githubusercontent.com/55936306/156480323-6dbdfadf-6c60-43d7-8cba-bc1b4138b76a.png)

且在我手动补全后ctrl+click无法直接跳转😭
![image](https://user-images.githubusercontent.com/55936306/156480709-35d1ed92-9cfe-4e9a-9982-bf1543401e93.png)

**Comment by KipSong** [comment]
重新启动vscode试试

**Comment by Mirrorgo** [comment]
我路径提示的问题我换了个路径补全的插件解决了,关于跳转的问题我反复测试感觉是我用到另一个插件的问题,我去提了个issue
https://github.com/apptools-lab/AppWorks/issues/988
