### ISSUE TITLE
<extensionurl>/xxxdir/xxx.html/routepath无法正常使用

### ISSUE THREAD

**Issue by Mirrorgo** [KipSong/vite-chrome-extension#7]
我在配置options.html页面的时候,发现一个问题:  
通常,在使用options页面的时候,会打开一个新的tab,结尾是.html,但是在这种情况下,react-router-dom无法正常运行, <extensionurl>/xxxdir/xxx.html/routepath无法正常使用  
我也尝试了官方针对多页应用的[解决方案](https://reactrouterdotcom.fly.dev/docs/en/v6/examples/multi-app),没有效果,因为他那种情况下xxx.html是不会显示在路径中的,
请问您是如何解决的,可否提供一些思路?  (我发现有的插件是用锚点实现的类似切换路由的效果)

如果您没有在options页面没有使用router的话,我再会去eact-router-dom提issue  
非常感谢

**Comment by KipSong** [comment]
你应当目录结构是root->options 页面下有个 index.html 页面。
